import { Product } from '../api/schemas/product';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Midnight Recovery Cloud Cream',
    description: 'A luxurious botanical facial cream formulated with squalane and evening primrose oil. Deeply restores lipids overnight for plump, radiant, and intensely hydrated skin by morning.',
    full_price: 5200,
    tester_price: 300,
    stock_full: 25,
    stock_tester: 50,
    image_url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800',
    category_id: 1,
    brand_id: 1,
    brand: { id: 1, name: "Kiehl's", description: 'Since 1851 New York' },
    category: { id: 1, name: 'Skincare', description: 'Face & Body Care' },
  },
  {
    id: 2,
    name: 'Coco Noir Eau De Parfum',
    description: 'An intimate, seductive fragrance with luminous bergamot, velvety May rose, and intoxicating patchouli. The magnetic expression of feminine black.',
    full_price: 14500,
    tester_price: 350,
    stock_full: 15,
    stock_tester: 40,
    image_url: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=800',
    category_id: 2,
    brand_id: 2,
    brand: { id: 2, name: 'Chanel', description: 'Haute Parfumerie Paris' },
    category: { id: 2, name: 'Fragrance', description: 'Fine Perfumes' },
  },
  {
    id: 3,
    name: 'Dior Addict Lip Glow Oil',
    description: 'Nourishing glossy lip oil infused with cherry oil for mirror shine and hydration. Adapts to the natural moisture of your lips for a custom rosy glow.',
    full_price: 3800,
    tester_price: 250,
    stock_full: 30,
    stock_tester: 60,
    image_url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800',
    category_id: 4,
    brand_id: 3,
    brand: { id: 3, name: 'Dior', description: 'House of Dior Paris' },
    category: { id: 4, name: 'Makeup', description: 'Luxury Cosmetics' },
  },
  {
    id: 4,
    name: 'Sauvage Eau de Parfum',
    description: 'Crisp Calabrian bergamot, sensual Papua New Guinean vanilla absolute, and radiant woody amber facets. An untamed olfactory signature.',
    full_price: 11500,
    tester_price: 350,
    stock_full: 20,
    stock_tester: 45,
    image_url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=800',
    category_id: 2,
    brand_id: 3,
    brand: { id: 3, name: 'Dior', description: 'House of Dior Paris' },
    category: { id: 2, name: 'Fragrance', description: 'Fine Perfumes' },
  },
  {
    id: 5,
    name: 'Bleu De Chanel Parfum',
    description: 'Intense woody aromatic fragrance with refined New Caledonian sandalwood and invigorating citrus zest. Pure masculine elegance.',
    full_price: 12800,
    tester_price: 350,
    stock_full: 18,
    stock_tester: 35,
    image_url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=800',
    category_id: 2,
    brand_id: 2,
    brand: { id: 2, name: 'Chanel', description: 'Haute Parfumerie Paris' },
    category: { id: 2, name: 'Fragrance', description: 'Fine Perfumes' },
  },
  {
    id: 6,
    name: 'Santal 33 Eau de Parfum',
    description: 'Iconic blend of smoky cardamom, violet, iris, and creamy cedarwood. Captures the great American myth with unforgettable spirit.',
    full_price: 24000,
    tester_price: 450,
    stock_full: 10,
    stock_tester: 25,
    image_url: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?q=80&w=800',
    category_id: 2,
    brand_id: 4,
    brand: { id: 4, name: 'Le Labo', description: 'Grasse New York' },
    category: { id: 2, name: 'Fragrance', description: 'Fine Perfumes' },
  },
];

export function getFallbackProduct(id: string | number | undefined): Product | undefined {
  if (!id) return INITIAL_PRODUCTS[0];
  const found = INITIAL_PRODUCTS.find(p => String(p.id) === String(id));
  return found || INITIAL_PRODUCTS[0];
}
